version: 0.2
phases:
  build:
    commands:
      - echo "========== Validate Apache configuration =========="
      - docker build -t redirector .
      - docker run redirector apachectl configtest
      - echo "========== Check Observatory score =========="
      - docker run -p 8080:80 -d redirector
      - git clone https://github.com/mozilla/http-observatory.git
      - cd http-observatory/
      - apt update && apt install -y python3-pip libpq-dev
      - pip3 install --upgrade .
      - pip3 install --upgrade -r requirements.txt
      - python3 httpobs/scripts/httpobs-local-scan localhost:8080
